### PR TITLE
Mongo datastores don't have a dataSourceName property.

### PR DESCRIPTION
**Pull request by jpalmer1026**

### CODE REVIEW

**Comment by smakela** [comment]
Thanks for the fix @jpalmer1026. I fixed the travis build because I found that your CI build failed.

https://github.com/robertoschwald/grails-audit-logging-plugin/pull/180

**Comment by robertoschwald** [comment]
Thanks for the PR. I didn't have time to look into the Mongo support, yet. I think we should support Mongo as an Audit logging backend as well. With your PR, an SQL backend would be needed as well, which mostly isn't what devs prefer. What do you think?

**Comment by smakela** [comment]
@robertoschwald This is just for the auditing actually work with mongodb plugin installed.
But yes there should be option to use only let's say mongodb or what ever datastore to store the audit data. That could be new feature.

**Comment by jpalmer1026** [comment]
@robertoschwald As @smakela mentioned, this PR is to just get around an issue where apps that are using both mongo and the audit logging plugin won't start. I like the idea of allowing users to specify the backend they'd like to use, but that's out of scope for this PR. Maybe we can add that one as a backlog issue.

**Comment by jpalmer1026** [comment]
Thanks for the merge 👍 Just out of curiosity, any idea when this will be pushed?

**Comment by robertoschwald** [comment]
soon ;-)

**Comment by jpalmer1026** [comment]
Did this break anyone's integration tests? I'm getting `Error creating bean with name 'hibernateDatastore': Bean instantiation via constructor failed` when I run the integration tests. The error goes away when I remove the plugin.

**Pull request merged**
