### PR TITLE
[WIP]: Split project in multiple plugins and refactored code

### PR DESCRIPTION
**Pull request by tkvw**
Motivation: 
I love the changes @longwa made to the code, but I think there are a couple of optimization that need to be done and want to allow a flexible stamp implementation. The code is now split in four plugins: 
 * audit-logging: the default audit-logging plugin. 
 * audit-stam-actor: adds `createdBy`, `lastUpdatedBy` fields to the entity and automatically populates them. 
 * audit-stamp-timestamp: adds Date type `dateCreated`, `lastUpdated`
 * audit-stamp-timestamp-java8: adds LocalDateTime type `dateCreated`, `lastUpdated`

Each plugin is `opt-out` by default (i.e.: requires you to implement `Auditable`), but has an `opt-in` counterpart, for example: `audit-plugin-applied`, this will automatically make all domainclasses auditable (there is a `@ExcludeFromAuditing` annotation to `opt-out` for specific domainclasses).

Changes/ TODO: 
- [X] Split project
- [X] Introduce plugin.yml in favour of `DefaultAuditLogConfig`
- [ ] Add unit tests
- [ ] Update docs
- [ ] Fix build files

### CODE REVIEW

**Comment by tkvw** [comment]
Is there a reason for a `lastUpdated` prop in the `AuditEvent` template?

**Comment by longwa** [comment]
I don't understand the purpose of the `@Audit` annotation just to change the includes and excludes. Is it just a usability thing? It doesn't seem particularly onerous to override a method on the domain object to change the behavior. We actually extend the entire `Auditable` trait and customize a few things across all of our audited entities. I think having the annotation just confuses the API.

You can already set `verbose = true` to enable verbose logging for all events. Not sure what was missing there. You can also set `verboseEvents = ...` and set it for specific types of events. If you set both, whatever you set for verboseEvents will win.

**Comment by tkvw** [comment]
> I don't understand the purpose of the @Audit annotation just to change the includes and excludes. Is it just a usability thing? It doesn't seem particularly onerous to override a method on the domain object to change the behavior. We actually extend the entire Auditable trait and customize a few things across all of our audited entities. I think having the annotation just confuses the API.

My idea is that if you allow to `include` and `exclude` on a domain instance (which is an exceptional use case) you always have to recalculate the included and excluded props for each auditEvent. I think the calculation done in the auditListener should be as minimal as possible. Best is that the props are `memoized` per domain class. I see no other elegant way to set the `include` and `exclude` props on the domain instance other than the `@Audit` annotation.

It actually does the same, but allows configuration at a higher more performant level. The lookup will be domain -> annotation -> config. (Domain will return null by default). 

But please correct me if I'm wrong.

**Comment by longwa** [comment]
The `getAuditablePropertyNames` in the Listener needs to be using the `AuditLogContext` instead of the configuration directly, otherwise you can't override the includes and excludes for a given context. For example, we have a part of our billing code where the system sets the invoice numbers after generating invoices, we exclude the `invoiceCode` column from auditing for that block using the `AuditLogContext`. I thought there was a test case for it, but maybe not.

**Comment by longwa** [comment]
The includes was in the global config as an example of what can be set. I use the DefaultSecurityConfig from SSC all the time to see what all the options are. I just included it for that purposes as an empty set.

**Comment by tkvw** [comment]
Thanks for the feedback on slack @longwa . I reverted back your changes (with some small changes applied)

**Comment by tkvw** [comment]
creating a new simplified PR>

**Pull request closed without merging**
