### PR TITLE
Make identifiers available in the maps during onChange event

### PR DESCRIPTION
**Pull request by dmahapatro**
Hi Rob

I believe I have missed this [commit](https://github.com/dmahapatro/grails-audit-logging-plugin/commit/55515d33d38c3592c4a4aee2f25e82d919ff892c) as part of my previous PR related to making identifiers available in the event hooks.

Can you please review and merge?

Thanks
Dhiraj

### CODE REVIEW

**Comment by dmahapatro** [comment]
@robertoschwald Will there be a way to merge this PR to version 1.0.5 and create a new release v1.0.6 to make it available for Grails 2 apps?

**Comment by robertoschwald** [comment]
Of course I can. 1.0.x code is maintained in branch 1.x_maintenance now. I merge into master (Grails 3) and into 1.x_maint branches.

**Comment by robertoschwald** [comment]
could you add a test for it so we don't miss anything? The former PR is quite old..

**Comment by dmahapatro** [comment]
Sure I can. Will do over the weekend.Today I have a tight schedule. Is that ok?

**Comment by robertoschwald** [comment]
perfect.

**Pull request merged**
