### PR TITLE
First Grails 4 version

### PR DESCRIPTION
**Pull request by JochenGraf**

### CODE REVIEW

**Comment by robertoschwald** [comment]
Hi Jochen, thanks for the PR. 
We work on a new approach for Grails 4. For this, we have a branch "feature/4.0.0_wip". It's queuing up audit logs using a TransactionSynchronizationAdapter and commits in a separate Transaction - but only if the main Transaction succeeds. For details see #183 
Branch for this is feature/4.0.0_wip
Whats missing currently is functional tests. Thats the reason why we didn't release a version for Grails 4.x, yet.

**Comment by JochenGraf** [comment]
Thanks, Robert! Now I notice the transaction problem. Please simply ignore the pull request. And I will look at the 4.0.0_wip branch.

**Comment by robertoschwald** [comment]
Ok, so I close this one. Sorry for this.

**Comment by nguyea006** [comment]
Hi M. Oschwald,
I know that this thread is closed, but I cannot find a way to contact you. I want to ask you 1 quick question, about your audit-logging plugin, I want to know if you have a plan to release a Grails 4 compatible version in a near future, like in the next year. I appreciate your feedback. Thanks for your help, your plugin is very easy to use and very efficient.

**Comment by robertoschwald** [comment]
Yes, we definitely will release for Grails 4.0.x. It's only a matter of resources when we find time to fix the tests. Hopefully early next year, but I can't promise..

**Comment by nguyea006** [comment]
Hi M. Oschwald,
Thank you very much for your answer. We'll wait for your new release impatiently. Very good product.

**Pull request closed without merging**
